### ISSUE TITLE
v2.10.0 startup regression for some configs/swagger specs

### ISSUE THREAD

**Issue by seanpk** [BlueOakJS/blueoak-server#101]
here is the reported startup stacktrace:
```
info: index.js - Starting blueoak-server v2.10.0 in development mode using Node.js v4.8.5
info: index.js - Clustering is disabled
info: monitor - Monitoring is disabled.
TypeError: Cannot read property 'properties' of undefined
    at Object.exports.getObjectsWithDiscriminator (/opt/PointSource/reserved-server/node_modules/blueoak-server/lib/swaggerUtil.js:44:34)
    at /opt/PointSource/reserved-server/node_modules/blueoak-server/lib/swaggerUtil.js:68:32
    at /opt/PointSource/reserved-server/node_modules/lodash/index.js:3073:15
    at baseForOwn (/opt/PointSource/reserved-server/node_modules/lodash/index.js:2046:14)
    at Function.forOwn (/opt/PointSource/reserved-server/node_modules/lodash/index.js:3378:16)
    at Object.exports.getObjectsWithDiscriminator (/opt/PointSource/reserved-server/node_modules/blueoak-server/lib/swaggerUtil.js:66:7)
    at _addDiscMapToSchema (/opt/PointSource/reserved-server/node_modules/blueoak-server/services/swagger.js:263:31)
    at /opt/PointSource/reserved-server/node_modules/blueoak-server/services/swagger.js:309:9
    at Array.forEach (native)
    at prepareDefinitionsForPolymorphicValidation (/opt/PointSource/reserved-server/node_modules/blueoak-server/services/swagger.js:307:16)
Startup failed [TypeError: Cannot read property 'properties' of undefined]
```

it looks like it is related to processing the swagger definitions to facilitate validation of objects against them...

**Comment by seanpk** [comment]
The specification in question appears to be invalid Swagger: the code is failing when an array is defined without the required "items" parameter.
(Relevant part of the spec: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#itemsObject)

I think it used to work "by luck".

So, while this is a regression, it's more like something broken got fixed.
Even so, I think it would be good to provide a more informative error message when server startup is prevented for this reason.

**Comment by seanpk** [comment]
While the traceback will basically be the same, the error message for swagger definitions like this will now be: `"OpenAPI array definitions require an "items" property; at model path: $definition.$propertyName"`
